---
title: "Copyright notice and disclaimer"
description: "About the legal use of content and materials published."
---

This data is published by EUROCONTROL for information purposes. 
It may be copied in whole or in part, provided that EUROCONTROL is mentioned as the source and it is not used for commercial purposes (i.e. for financial gain). The information in this document may not be modified without prior written permission from EUROCONTROL.

The information does not necessarily reflect the official views or policy of
<small style="font-variant: small-caps;">EUROCONTROL</small>,
which makes no warranty, either implied or expressed, for the information contained in
this document, including its accuracy, completeness or usefulness.

Every effort has been made to ensure that the information and analysis contained on this website
are as accurate and complete as possible.
Despite these precautions, should you find any errors or inconsistencies or
if you have any questions then please contact us at:
[Performance Review Unit](mailto:PRU-Support@eurocontrol.int) (PRU-Support@eurocontrol.int).
