---
title: ANSP Performance Analysis Tools
description: "A collection of tools and dashboards which are useful for Air Navigation Service Provider (ANSP) performance monitoring."
date: '2020-05-15'
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>

<br>

::: {class="container"}
:::: {class="row"}
::::: {class="card-deck"}

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img = "ansp_db.png",
  link = "/dashboard/stakeholder/ansp/ansp_db",
  title = "ANSP Operational Performance Dashboard",
  text = "Monthly overview of operational ANSP performance across a wide spectrum of indicators.<br><br> <div class='badge-container'><span class='badge badge-secondary'>General Performance</span></div>",
  alt = "ANSP performance dashboard",
  command = "Resize",
  options = "300x",
  class = "mb-2"
)
```

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img = "acc_traff_db.png",
  link = "https://www.eurocontrol.int/Economics/DailyTrafficVariation-ACCs.html",
  title = "Daily Traffic Variation at State and ACC Level",
  text = "Monitor the daily traffic variation at at State and ACC level since the start of the COVID-19 crisis. <br> <div class='badge-container'><span class='badge badge-primary'>Traffic</span></div>",
  alt = "Daily traffic @ ACCs",
  command = "Resize",
  options = "300x",
  class = "mb-2"
)
```

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img = "ace_db.png",
  link = "https://www.eurocontrol.int/ACE/ACE-Home.html",
  title = "ATM Cost-Effectiveness Dashboard",
  text = "Analyse information and data on ANSP cost-effectiveness performance (2002-2020). <br> <div class='badge-container'><span class='badge badge-success'>Economics</span></div>",
  alt = "ACE Dashboard",
  command = "Resize",
  options = "300x",
  class = "mb-2"
)
```

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img = "fin_db_2022_thmb.png",
  link = "/economics/finance/",
  title = "ANSP Financial Dashboard <i class='fas fa-xs fa-external-link-alt'></i>",
  text = "Explore key financial information and indicators for European ANSPs. <br> <div class='badge-container'><span class='badge badge-success'>Economics</span></div>",
  alt = "ANSPs Financial Dashboard",
  command = "Resize",
  options = "300x",
  class = "mb-2"
)
```

:::::
::::
:::

<br>

::: {class="container"}
:::: {class="row"}
::::: {class="card-deck"}

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img = "ectl_3.jpg",
  link = "/capacity/atfm_ert/",
  title = "En-route ATFM Delays",
  text = "Analyse the en-route ATFM delays. <br> <div class='badge-container'><span class='badge badge-warning'>Capacity & Delays</span></div>",
  alt = "ATFM en-route delays",
  command = "Resize",
  options = "300x",
  class = "mb-2"
)
```

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img = "cdo_icon.jpg",
  link = "/efficiency/vfe/",
  title = "CCO and CDO Overview",
  text = "Explore the vertical flight efficiency during climb (CCO) and descent (CDO). <br> <div class='badge-container'><span class='badge badge-info'>Efficiency</span></div>",
  alt = "Vertical flight efficiency @ airports",
  command = "Resize",
  options = "300x",
  class = "mb-2"
)
```

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img = "apt_asma.jpg",
  link = "/efficiency/asma/",
  title = "Additional ASMA Time",
  text = "Find out about the efficiency in the Arrival Sequencing and Metering Area (ASMA). <br> <div class='badge-container'><span class='badge badge-info'>Efficiency</span></div>",
  alt = "ASMA additional time @ airports",
  command = "Resize",
  options = "300x",
  class = "mb-2"
)
```

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img = "apt_taxi.jpg",
  link = "/efficiency/taxiout/",
  title = "Additional Taxi-Out Time",
  text = "See the taxi-out efficiency at airports. <br> <div class='badge-container'><span class='badge badge-info'>Efficiency</span></div>",
  alt = "Taxi-out additional time @ airports",
  command = "Resize",
  options = "300x",
  class = "mb-2"
)
```

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img = "ectl_mirror.jpg",
  link = "https://www.eurocontrol.int/tool/mirror",
  title = "MIRROR - Operational Decision Support Tool <i class='fas fa-xs fa-external-link-alt'></i>",
  text = "Check out the new tool that helps stakeholders predict and mitigate delays. <br><br> <div class='badge-container'><span class='badge badge-warning'>Capacity & Delays</span></div>",
  alt = "MIRROR - Operational decision support tool",
  command = "Resize",
  options = "300x",
  class = "mb-2"
)
```

:::::
::::
:::

<style>
.card-deck .card .badge-container {
  position: absolute;
  bottom: 0.75rem;
  left: 1.2rem;
  display: block;
}
</style>

<script>
    function resizeIframe(obj) {
      obj.style.height = obj.contentWindow.document.documentElement.scrollHeight + 'px';
    }
</script>

<style type="text/css">
.img-responsive {
    margin: 0 auto;
    max-width: 75%
}

.resp-container {
    position: relative;
    overflow: hidden;
    padding-top: 60.0%;
}

.resp-iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 150%;
    border: 0;
}
</style>
