---
title: OBT - Off-Block Time
slug: obt
---


Airport Collaborative Decision-Making ([A-CDM](a-cdm.qmd))
describes different terms for OBT:

* [SOBT (Scheduled Off Block Time)](sobt.qmd): The time that an aircraft is scheduled
  to depart from the parking position.
* [EOBT (Estimated Off Block Time)](eobt.qmd): The estimated
  time that an aircraft will start movement associated with departure.
* [TOBT (Target Off Block Time)](tobt.qmd): The time that an
  aircraft Operator or Ground handler estimates that an aircraft will be
  ready to startup/pushback immediately upon reception of clearance from the tower.
* TSAT (Target Start Up Approval Time): The time provided by ATC taking into
  account TOBT, CTOT and/or the traffic situation that an aircraft can expect start up/push back approval.
* [AOBT (Actual Off Block Time)](aobt.qmd): The time the aircraft pushes back/vacates
  parking position.


## See Also

* [Airport Collaborative Decision-Making - A-CDM](a-cdm.qmd)
* [AOBT - Actual Off Block Time](aobt.qmd)
* [EOBT - Estimated Off Block Time](eobt.qmd)
* [SOBT - Scheduled Off Block Time](sobt.qmd)
* [TOBT - Target Off Block Time][tobt]
