---
title: RAD - Route Availability Document
slug: rad
---

The Route Availability Document is a flight-planning document, which integrates
both structural and [ATFCM](atfcm.qmd) requirements, geographically and vertically,
following an appropriate [collaborative decision making](cdm.qmd) process between
the [network manager](nm-cfmu.qmd) and the operational stakeholders.
It is a 'central' source of airspace utilisation rules and availability
defined and communicated by the [ANSP](ansp.qmd)s, 56 days before the start of the
concerned Aeronautical Information Regulation and Control ([AIRAC](airac.qmd)) cycle.

It facilitates flight planning in order to improve
Air traffic Flow and Capacity Management ([ATFCM](atfcm.qmd)) while allowing
aircraft operators' flight planning flexibility.

It also enables [ANSP](ansp.qmd)s to maximise capacity and reduce complexity by defining
restrictions that prevent disruption to the organised system of major traffic
flows through the congested areas with due regard to aircraft operators
requirements.

## See Also

* {{< a_blank ectrl "Airspace utilisation" "https://www.eurocontrol.int/function/airspace-utilisation" >}}
* [ATFCM](atfcm.qmd).
